apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  labels:
    app: python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: us-central1-docker.pkg.dev/dev-order-453010-h4/my-docker/my-python-app
        ports:
        - containerPort: 8080
