name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
        
    - name: Set up Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        install_components: 'kubectl'  
        
    - name: Configure Docker authentication
      run: |-
        gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build and push Docker image to GCR
      run: |-
        IMAGE_NAME="us-central1-docker.pkg.dev/dev-order-453010-h4/my-docker/my-python-app"
        docker build -t $IMAGE_NAME:latest .
        docker push $IMAGE_NAME:latest

    - name: Enable GKE auth plugin usage
      run: echo "USE_GKE_GCLOUD_AUTH_PLUGIN=True" >> $GITHUB_ENV     

    - name: Make gke-gcloud-auth-plugin available
      run: |
        export GCLOUD_SDK_PATH=$(gcloud info --format="value(installation.sdk_root)")
        export PATH="$GCLOUD_SDK_PATH/bin:$PATH"
        echo "USE_GKE_GCLOUD_AUTH_PLUGIN=True" >> $GITHUB_ENV

    - name: Install gke-gcloud-auth-plugin
      run: |
        gcloud components install gke-gcloud-auth-plugin --quiet
        echo "USE_GKE_GCLOUD_AUTH_PLUGIN=True" >> $GITHUB_ENV

        
    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials prod-cluster \
          --region us-central1 \
          --project ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy to GKE with kubectl
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
